fixes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -208,10 +208,14 @@ jobs:
       - run:
           name: Send migration status to kvdb.io OR memstash.io
           command: |   
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt;
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-                echo "Migrations dumped successfully.";
-                curl --insecure https://kvdb.io/HVaC7zh31tMNiAh9C5i6QN/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1';
+                cat ~/project/backend/migrations_dump.txt
+                echo "Migrations dumped successfully."
+                curl --insecure https://kvdb.io/HVaC7zh31tMNiAh9C5i6QN/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            else 
+              echo "failed to execute migration"
+              exit 1    
             fi
       - destroy-environment
   deploy-frontend:
